/**
 * 货币元数据
 * 包含法币和加密货币的信息
 *
 * 复合代币（如 ETHUSDT、BSCUSDC）从 tokens.ts 的 TOKENS 配置自动推导，
 * 无需手动维护，新增链或代币只需更新 tokens.ts 即可。
 */

import type { CurrencyInfo } from '../types/currency';
import { TOKENS, CHAINS } from './tokens';

/**
 * 基础加密货币列表
 * 仅包含不在 TOKENS 中的币种（如 BCH、CFX、ZEC）和需要特殊配置的币种（如 MATICMBZ）
 * TOKENS 中定义的币种（含复合代币）会自动生成
 */
const BASE_CRYPTO_CURRENCIES: CurrencyInfo[] = [
  {
    code: 'BTC',
    symbol: '₿',
    symbolNative: '₿',
    name: 'Bitcoin',
    namePlural: 'BTC',
    decimals: 8,
    rounding: 0,
    type: 'crypto',
  },
  {
    code: 'ETH',
    symbol: 'Ξ',
    symbolNative: 'Ξ',
    name: 'Ethereum',
    namePlural: 'ETH',
    decimals: 18,
    rounding: 0,
    type: 'crypto',
  },
  {
    code: 'USDT',
    symbol: '₮',
    symbolNative: '₮',
    name: 'Tether',
    namePlural: 'USDT',
    decimals: 6,
    rounding: 0,
    type: 'crypto',
  },
  {
    code: 'USDC',
    symbol: 'USDC',
    symbolNative: '$',
    name: 'USD Coin',
    namePlural: 'USDC',
    decimals: 6,
    rounding: 0,
    type: 'crypto',
  },
  // 以下币种不在 TOKENS 中，需要手动定义
  {
    code: 'MATICMBZ',
    symbol: 'MBZ',
    symbolNative: '$',
    name: 'Mobazha Token',
    namePlural: 'MATICMBZ',
    decimals: 18,
    rounding: 0,
    type: 'crypto',
  },
  {
    code: 'BCH',
    symbol: '₿',
    symbolNative: '₿',
    name: 'Bitcoin Cash',
    namePlural: 'BCH',
    decimals: 8,
    rounding: 0,
    type: 'crypto',
  },
  {
    code: 'CFX',
    symbol: 'CFX',
    symbolNative: 'CFX',
    name: 'Conflux',
    namePlural: 'CFX',
    decimals: 18,
    rounding: 0,
    type: 'crypto',
  },
  {
    code: 'LTC',
    symbol: 'Ł',
    symbolNative: 'Ł',
    name: 'Litecoin',
    namePlural: 'LTC',
    decimals: 8,
    rounding: 0,
    type: 'crypto',
  },
  {
    code: 'ZEC',
    symbol: 'ⓩ',
    symbolNative: 'ⓩ',
    name: 'Zcash',
    namePlural: 'ZEC',
    decimals: 8,
    rounding: 0,
    type: 'crypto',
  },
];

// ============ 从 TOKENS 自动生成复合代币条目 ============

// 基础币种符号/名称查找表
const _baseCurrencyLookup = new Map<string, CurrencyInfo>();
BASE_CRYPTO_CURRENCIES.forEach(c => _baseCurrencyLookup.set(c.code.toUpperCase(), c));

// 链名称查找表（用于生成友好名称，如 "Tether (Ethereum)"）
const _chainNameLookup = new Map<string, string>();
CHAINS.forEach(c => {
  if (c.type === 'blockchain') _chainNameLookup.set(c.id, c.name);
});

/**
 * 从 TOKENS 自动生成的加密货币条目
 * 包括原生代币（BNB, SOL, MATIC 等）和复合代币（ETHUSDT, BSCUSDC 等）
 */
const _autoGeneratedCrypto: CurrencyInfo[] = TOKENS.filter(
  t => !_baseCurrencyLookup.has(t.id.toUpperCase())
).map(t => {
  const baseInfo = _baseCurrencyLookup.get(t.token.toUpperCase());
  const chainName = _chainNameLookup.get(t.chain) || t.chain;
  const isComposite = t.id.toUpperCase() !== t.token.toUpperCase();

  return {
    code: t.id,
    symbol: baseInfo?.symbol || t.token,
    symbolNative: baseInfo?.symbolNative || t.token,
    name: isComposite ? `${baseInfo?.name || t.token} (${chainName})` : baseInfo?.name || t.token,
    namePlural: t.id,
    decimals: t.decimals,
    rounding: 0,
    type: 'crypto' as const,
  };
});

/**
 * 完整加密货币列表（基础 + 自动生成）
 */
export const CRYPTO_CURRENCIES: CurrencyInfo[] = [
  ...BASE_CRYPTO_CURRENCIES,
  ..._autoGeneratedCrypto,
];

/**
 * 法币列表
 */
export const FIAT_CURRENCIES: CurrencyInfo[] = [
  {
    code: 'USD',
    symbol: '$',
    symbolNative: '$',
    name: '🇺🇸 US Dollar',
    namePlural: 'US dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'EUR',
    symbol: '€',
    symbolNative: '€',
    name: '🇪🇺 Euro',
    namePlural: 'euros',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'CNY',
    symbol: 'CN¥',
    symbolNative: 'CN¥',
    name: '🇨🇳 Chinese Yuan',
    namePlural: 'Chinese yuan',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'GBP',
    symbol: '£',
    symbolNative: '£',
    name: '🇬🇧 British Pound Sterling',
    namePlural: 'British pounds sterling',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'JPY',
    symbol: '¥',
    symbolNative: '￥',
    name: '🇯🇵 Japanese Yen',
    namePlural: 'Japanese yen',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'CAD',
    symbol: 'CA$',
    symbolNative: '$',
    name: '🇨🇦 Canadian Dollar',
    namePlural: 'Canadian dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'AUD',
    symbol: 'AU$',
    symbolNative: '$',
    name: '🇦🇺 Australian Dollar',
    namePlural: 'Australian dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'CHF',
    symbol: 'CHF',
    symbolNative: 'CHF',
    name: '🇨🇭 Swiss Franc',
    namePlural: 'Swiss francs',
    decimals: 2,
    rounding: 0.05,
    type: 'fiat',
  },
  {
    code: 'HKD',
    symbol: 'HK$',
    symbolNative: '$',
    name: '🇭🇰 Hong Kong Dollar',
    namePlural: 'Hong Kong dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'SGD',
    symbol: 'S$',
    symbolNative: '$',
    name: '🇸🇬 Singapore Dollar',
    namePlural: 'Singapore dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'KRW',
    symbol: '₩',
    symbolNative: '₩',
    name: '🇰🇷 South Korean Won',
    namePlural: 'South Korean won',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'INR',
    symbol: 'Rs',
    symbolNative: 'টকা',
    name: '🇮🇳 Indian Rupee',
    namePlural: 'Indian rupees',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BRL',
    symbol: 'R$',
    symbolNative: 'R$',
    name: '🇧🇷 Brazilian Real',
    namePlural: 'Brazilian reals',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MXN',
    symbol: 'MX$',
    symbolNative: '$',
    name: '🇲🇽 Mexican Peso',
    namePlural: 'Mexican pesos',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'RUB',
    symbol: 'RUB',
    symbolNative: 'руб.',
    name: '🇷🇺 Russian Ruble',
    namePlural: 'Russian rubles',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'ZAR',
    symbol: 'R',
    symbolNative: 'R',
    name: '🇿🇦 South African Rand',
    namePlural: 'South African rand',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'TRY',
    symbol: 'TL',
    symbolNative: 'TL',
    name: '🇹🇷 Turkish Lira',
    namePlural: 'Turkish Lira',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'THB',
    symbol: '฿',
    symbolNative: '฿',
    name: '🇹🇭 Thai Baht',
    namePlural: 'Thai baht',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'TWD',
    symbol: 'NT$',
    symbolNative: 'NT$',
    name: '🇹🇼 New Taiwan Dollar',
    namePlural: 'New Taiwan dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'VND',
    symbol: '₫',
    symbolNative: '₫',
    name: '🇻🇳 Vietnamese Dong',
    namePlural: 'Vietnamese dong',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'AED',
    symbol: 'AED',
    symbolNative: 'د.إ.‏',
    name: '🇦🇪 United Arab Emirates Dirham',
    namePlural: 'UAE dirhams',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'AFN',
    symbol: 'Af',
    symbolNative: '؋',
    name: '🇦🇫 Afghan Afghani',
    namePlural: 'Afghan Afghanis',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'ALL',
    symbol: 'ALL',
    symbolNative: 'Lek',
    name: '🇦🇱 Albanian Lek',
    namePlural: 'Albanian lekë',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'AMD',
    symbol: 'AMD',
    symbolNative: 'դdelays.',
    name: '🇦🇲 Armenian Dram',
    namePlural: 'Armenian drams',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'ARS',
    symbol: 'AR$',
    symbolNative: '$',
    name: '🇦🇷 Argentine Peso',
    namePlural: 'Argentine pesos',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'AZN',
    symbol: 'man.',
    symbolNative: 'ман.',
    name: '🇦🇿 Azerbaijani Manat',
    namePlural: 'Azerbaijani manats',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BHD',
    symbol: 'BD',
    symbolNative: 'د.ب.‏',
    name: 'Bahraini Dinar',
    namePlural: 'Bahraini dinars',
    decimals: 3,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BDT',
    symbol: 'Tk',
    symbolNative: '৳',
    name: '🇧🇩 Bangladeshi Taka',
    namePlural: 'Bangladeshi takas',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BAM',
    symbol: 'KM',
    symbolNative: 'KM',
    name: '🇧🇦 Bosnia-Herzegovina Convertible Mark',
    namePlural: 'Bosnia-Herzegovina convertible marks',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BGN',
    symbol: 'BGN',
    symbolNative: 'лв.',
    name: '🇧🇬 Bulgarian Lev',
    namePlural: 'Bulgarian leva',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BIF',
    symbol: 'FBu',
    symbolNative: 'FBu',
    name: '🇧🇮 Burundian Franc',
    namePlural: 'Burundian francs',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BND',
    symbol: 'BN$',
    symbolNative: '$',
    name: '🇧🇳 Brunei Dollar',
    namePlural: 'Brunei dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BOB',
    symbol: 'Bs',
    symbolNative: 'Bs',
    name: '🇧🇴 Bolivian Boliviano',
    namePlural: 'Bolivian bolivianos',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BWP',
    symbol: 'BWP',
    symbolNative: 'P',
    name: '🇧🇼 Botswanan Pula',
    namePlural: 'Botswanan pulas',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BYR',
    symbol: 'BYR',
    symbolNative: 'BYR',
    name: '🇧🇾 Belarusian Ruble',
    namePlural: 'Belarusian rubles',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'BZD',
    symbol: 'BZ$',
    symbolNative: '$',
    name: '🇧🇿 Belize Dollar',
    namePlural: 'Belize dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'CDF',
    symbol: 'CDF',
    symbolNative: 'FrCD',
    name: '🇩🇴 Congolese Franc',
    namePlural: 'Congolese francs',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'CLP',
    symbol: 'CL$',
    symbolNative: '$',
    name: '🇨🇱 Chilean Peso',
    namePlural: 'Chilean pesos',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'COP',
    symbol: 'CO$',
    symbolNative: '$',
    name: '🇨🇴 Colombian Peso',
    namePlural: 'Colombian pesos',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'CRC',
    symbol: '₡',
    symbolNative: '₡',
    name: '🇨🇷 Costa Rican Colón',
    namePlural: 'Costa Rican colóns',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'CVE',
    symbol: 'CV$',
    symbolNative: 'CV$',
    name: '🇨🇻 Cape Verdean Escudo',
    namePlural: 'Cape Verdean escudos',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'CZK',
    symbol: 'Kč',
    symbolNative: 'Kč',
    name: '🇨🇿 Czech Republic Koruna',
    namePlural: 'Czech Republic korunas',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'DJF',
    symbol: 'Fdj',
    symbolNative: 'Fdj',
    name: '🇩🇯 Djiboutian Franc',
    namePlural: 'Djiboutian francs',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'DKK',
    symbol: 'Dkr',
    symbolNative: 'kr',
    name: '🇩🇰 Danish Krone',
    namePlural: 'Danish kroner',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'DOP',
    symbol: 'RD$',
    symbolNative: 'RD$',
    name: '🇩🇴 Dominican Peso',
    namePlural: 'Dominican pesos',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'DZD',
    symbol: 'DA',
    symbolNative: 'د.ج.‏',
    name: '🇩🇿 Algerian Dinar',
    namePlural: 'Algerian dinars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'EEK',
    symbol: 'Ekr',
    symbolNative: 'kr',
    name: '🇪🇪 Estonian Kroon',
    namePlural: 'Estonian kroons',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'EGP',
    symbol: 'EGP',
    symbolNative: 'ج.م.‏',
    name: '🇪🇬 Egyptian Pound',
    namePlural: 'Egyptian pounds',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'ERN',
    symbol: 'Nfk',
    symbolNative: 'Nfk',
    name: '🇪🇷 Eritrean Nakfa',
    namePlural: 'Eritrean nakfas',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'ETB',
    symbol: 'Br',
    symbolNative: 'Br',
    name: '🇪🇹 Ethiopian Birr',
    namePlural: 'Ethiopian birrs',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'GEL',
    symbol: 'GEL',
    symbolNative: 'GEL',
    name: '🇬🇪 Georgian Lari',
    namePlural: 'Georgian laris',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'GHS',
    symbol: 'GH₵',
    symbolNative: 'GH₵',
    name: '🇬🇭 Ghanaian Cedi',
    namePlural: 'Ghanaian cedis',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'GNF',
    symbol: 'FG',
    symbolNative: 'FG',
    name: '🇬🇳 Guinean Franc',
    namePlural: 'Guinean francs',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'GTQ',
    symbol: 'GTQ',
    symbolNative: 'Q',
    name: '🇬🇹 Guatemalan Quetzal',
    namePlural: 'Guatemalan quetzals',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'HNL',
    symbol: 'HNL',
    symbolNative: 'L',
    name: '🇭🇳 Honduran Lempira',
    namePlural: 'Honduran lempiras',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'HRK',
    symbol: 'kn',
    symbolNative: 'kn',
    name: '🇭🇷 Croatian Kuna',
    namePlural: 'Croatian kunas',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'HUF',
    symbol: 'Ft',
    symbolNative: 'Ft',
    name: '🇭🇺 Hungarian Forint',
    namePlural: 'Hungarian forints',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'IDR',
    symbol: 'Rp',
    symbolNative: 'Rp',
    name: '🇮🇩 Indonesian Rupiah',
    namePlural: 'Indonesian rupiahs',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'ILS',
    symbol: '₪',
    symbolNative: '₪',
    name: '🇮🇱 Israeli New Sheqel',
    namePlural: 'Israeli new sheqels',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'IQD',
    symbol: 'IQD',
    symbolNative: 'د.ع.‏',
    name: '🇮🇶 Iraqi Dinar',
    namePlural: 'Iraqi dinars',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'IRR',
    symbol: 'IRR',
    symbolNative: '﷼',
    name: '🇮🇷 Iranian Rial',
    namePlural: 'Iranian rials',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'ISK',
    symbol: 'Ikr',
    symbolNative: 'kr',
    name: '🇮🇸 Icelandic Króna',
    namePlural: 'Icelandic krónur',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'JMD',
    symbol: 'J$',
    symbolNative: '$',
    name: '🇯🇲 Jamaican Dollar',
    namePlural: 'Jamaican dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'JOD',
    symbol: 'JD',
    symbolNative: 'د.أ.‏',
    name: '🇯🇴 Jordanian Dinar',
    namePlural: 'Jordanian dinars',
    decimals: 3,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'KES',
    symbol: 'Ksh',
    symbolNative: 'Ksh',
    name: '🇰🇪 Kenyan Shilling',
    namePlural: 'Kenyan shillings',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'KHR',
    symbol: 'KHR',
    symbolNative: '៛',
    name: '🇰🇭 Cambodian Riel',
    namePlural: 'Cambodian riels',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'KMF',
    symbol: 'CF',
    symbolNative: 'FC',
    name: '🇰🇲 Comorian Franc',
    namePlural: 'Comorian francs',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'KWD',
    symbol: 'KD',
    symbolNative: 'د.ك.‏',
    name: '🇰🇼 Kuwaiti Dinar',
    namePlural: 'Kuwaiti dinars',
    decimals: 3,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'KZT',
    symbol: 'KZT',
    symbolNative: 'тңг.',
    name: '🇰🇿 Kazakhstani Tenge',
    namePlural: 'Kazakhstani tenges',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'LBP',
    symbol: 'LB£',
    symbolNative: 'ل.ل.‏',
    name: '🇱🇧 Lebanese Pound',
    namePlural: 'Lebanese pounds',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'LKR',
    symbol: 'SLRs',
    symbolNative: 'SL Re',
    name: '🇱🇰 Sri Lankan Rupee',
    namePlural: 'Sri Lankan rupees',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'LTL',
    symbol: 'Lt',
    symbolNative: 'Lt',
    name: '🇱🇹 Lithuanian Litas',
    namePlural: 'Lithuanian litai',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'LVL',
    symbol: 'Ls',
    symbolNative: 'Ls',
    name: '🇱🇻 Latvian Lats',
    namePlural: 'Latvian lati',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'LYD',
    symbol: 'LD',
    symbolNative: 'د.ل.‏',
    name: '🇱🇾 Libyan Dinar',
    namePlural: 'Libyan dinars',
    decimals: 3,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MAD',
    symbol: 'MAD',
    symbolNative: 'د.م.‏',
    name: '🇲🇦 Moroccan Dirham',
    namePlural: 'Moroccan dirhams',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MDL',
    symbol: 'MDL',
    symbolNative: 'MDL',
    name: '🇲🇩 Moldovan Leu',
    namePlural: 'Moldovan lei',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MGA',
    symbol: 'MGA',
    symbolNative: 'MGA',
    name: '🇲🇬 Malagasy Ariary',
    namePlural: 'Malagasy Ariaries',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MKD',
    symbol: 'MKD',
    symbolNative: 'MKD',
    name: '🇲🇰 Macedonian Denar',
    namePlural: 'Macedonian denari',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MMK',
    symbol: 'MMK',
    symbolNative: 'K',
    name: '🇲🇲 Myanma Kyat',
    namePlural: 'Myanma kyats',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MOP',
    symbol: 'MOP$',
    symbolNative: 'MOP$',
    name: '🇲🇴 Macanese Pataca',
    namePlural: 'Macanese patacas',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MUR',
    symbol: 'MURs',
    symbolNative: 'MURs',
    name: '🇲🇺 Mauritian Rupee',
    namePlural: 'Mauritian rupees',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MYR',
    symbol: 'RM',
    symbolNative: 'RM',
    name: '🇲🇾 Malaysian Ringgit',
    namePlural: 'Malaysian ringgits',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'MZN',
    symbol: 'MTn',
    symbolNative: 'MTn',
    name: '🇲🇿 Mozambican Metical',
    namePlural: 'Mozambican meticals',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'NAD',
    symbol: 'N$',
    symbolNative: 'N$',
    name: '🇳🇦 Namibian Dollar',
    namePlural: 'Namibian dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'NGN',
    symbol: '₦',
    symbolNative: '₦',
    name: '🇳🇪 Nigerian Naira',
    namePlural: 'Nigerian nairas',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'NIO',
    symbol: 'C$',
    symbolNative: 'C$',
    name: '🇳🇮 Nicaraguan Córdoba',
    namePlural: 'Nicaraguan córdobas',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'NOK',
    symbol: 'Nkr',
    symbolNative: 'kr',
    name: '🇳🇴 Norwegian Krone',
    namePlural: 'Norwegian kroner',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'NPR',
    symbol: 'NPRs',
    symbolNative: 'नेरू',
    name: '🇳🇵 Nepalese Rupee',
    namePlural: 'Nepalese rupees',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'NZD',
    symbol: 'NZ$',
    symbolNative: '$',
    name: '🇳🇿 New Zealand Dollar',
    namePlural: 'New Zealand dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'OMR',
    symbol: 'OMR',
    symbolNative: 'ر.ع.‏',
    name: '🇴🇲 Omani Rial',
    namePlural: 'Omani rials',
    decimals: 3,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'PAB',
    symbol: 'B/.',
    symbolNative: 'B/.',
    name: '🇵🇦 Panamanian Balboa',
    namePlural: 'Panamanian balboas',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'PEN',
    symbol: 'S/.',
    symbolNative: 'S/.',
    name: '🇵🇪 Peruvian Nuevo Sol',
    namePlural: 'Peruvian nuevos soles',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'PHP',
    symbol: '₱',
    symbolNative: '₱',
    name: '🇵🇭 Philippine Peso',
    namePlural: 'Philippine pesos',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'PKR',
    symbol: 'PKRs',
    symbolNative: '₨',
    name: '🇵🇰 Pakistani Rupee',
    namePlural: 'Pakistani rupees',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'PLN',
    symbol: 'zł',
    symbolNative: 'zł',
    name: '🇵🇱 Polish Zloty',
    namePlural: 'Polish zlotys',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'PYG',
    symbol: '₲',
    symbolNative: '₲',
    name: '🇵🇾 Paraguayan Guarani',
    namePlural: 'Paraguayan guaranis',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'QAR',
    symbol: 'QR',
    symbolNative: 'ر.ق.‏',
    name: '🇶🇦 Qatari Rial',
    namePlural: 'Qatari rials',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'RON',
    symbol: 'RON',
    symbolNative: 'RON',
    name: '🇷🇴 Romanian Leu',
    namePlural: 'Romanian lei',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'RSD',
    symbol: 'din.',
    symbolNative: 'дин.',
    name: '🇷🇸 Serbian Dinar',
    namePlural: 'Serbian dinars',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'RWF',
    symbol: 'RWF',
    symbolNative: 'FR',
    name: '🇷🇼 Rwandan Franc',
    namePlural: 'Rwandan francs',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'SAR',
    symbol: 'SR',
    symbolNative: 'ر.س.‏',
    name: '🇸🇦 Saudi Riyal',
    namePlural: 'Saudi riyals',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'SDG',
    symbol: 'SDG',
    symbolNative: 'SDG',
    name: '🇸🇩 Sudanese Pound',
    namePlural: 'Sudanese pounds',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'SEK',
    symbol: 'Skr',
    symbolNative: 'kr',
    name: '🇸🇪 Swedish Krona',
    namePlural: 'Swedish kronor',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'SOS',
    symbol: 'Ssh',
    symbolNative: 'Ssh',
    name: '🇸🇴 Somali Shilling',
    namePlural: 'Somali shillings',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'SYP',
    symbol: 'SY£',
    symbolNative: 'ل.س.‏',
    name: '🇸🇾 Syrian Pound',
    namePlural: 'Syrian pounds',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'TND',
    symbol: 'DT',
    symbolNative: 'د.ت.‏',
    name: '🇹🇳 Tunisian Dinar',
    namePlural: 'Tunisian dinars',
    decimals: 3,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'TOP',
    symbol: 'T$',
    symbolNative: 'T$',
    name: '🇹🇴 Tongan Paʻanga',
    namePlural: 'Tongan paʻanga',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'TTD',
    symbol: 'TT$',
    symbolNative: '$',
    name: '🇹🇹 Trinidad and Tobago Dollar',
    namePlural: 'Trinidad and Tobago dollars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'TZS',
    symbol: 'TSh',
    symbolNative: 'TSh',
    name: '🇹🇿 Tanzanian Shilling',
    namePlural: 'Tanzanian shillings',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'UAH',
    symbol: '₴',
    symbolNative: '₴',
    name: '🇺🇦 Ukrainian Hryvnia',
    namePlural: 'Ukrainian hryvnias',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'UGX',
    symbol: 'USh',
    symbolNative: 'USh',
    name: '🇺🇬 Ugandan Shilling',
    namePlural: 'Ugandan shillings',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'UYU',
    symbol: '$U',
    symbolNative: '$',
    name: '🇺🇾 Uruguayan Peso',
    namePlural: 'Uruguayan pesos',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'UZS',
    symbol: 'UZS',
    symbolNative: 'UZS',
    name: '🇺🇿 Uzbekistan Som',
    namePlural: 'Uzbekistan som',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'VES',
    symbol: 'Bs.F.',
    symbolNative: 'Bs.F.',
    name: '🇻🇪 Venezuelan Bolívar',
    namePlural: 'Venezuelan bolívars',
    decimals: 2,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'XAF',
    symbol: 'FCFA',
    symbolNative: 'FCFA',
    name: '🌍 CFA Franc BEAC',
    namePlural: 'CFA francs BEAC',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'XOF',
    symbol: 'CFA',
    symbolNative: 'CFA',
    name: '🌍 CFA Franc BCEAO',
    namePlural: 'CFA francs BCEAO',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'YER',
    symbol: 'YR',
    symbolNative: 'ر.ي.‏',
    name: '🇾🇪 Yemeni Rial',
    namePlural: 'Yemeni rials',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
  {
    code: 'ZMK',
    symbol: 'ZK',
    symbolNative: 'ZK',
    name: '🇿🇲 Zambian Kwacha',
    namePlural: 'Zambian kwachas',
    decimals: 0,
    rounding: 0,
    type: 'fiat',
  },
];

/**
 * 所有货币列表
 */
export const ALL_CURRENCIES: CurrencyInfo[] = [...CRYPTO_CURRENCIES, ...FIAT_CURRENCIES];

/**
 * 货币代码到信息的映射
 */
const currencyMap = new Map<string, CurrencyInfo>();
ALL_CURRENCIES.forEach(currency => {
  currencyMap.set(currency.code.toUpperCase(), currency);
});

/**
 * 根据货币代码获取货币信息
 */
export function getCurrencyByCode(code: string): CurrencyInfo | undefined {
  return currencyMap.get(code.toUpperCase());
}

/**
 * 解析复合代币码，获取其基础货币信息
 * 例如：ETHUSDT → USDT 的 CurrencyInfo, BSCUSDC → USDC 的 CurrencyInfo
 * 如果不是复合代币码或找不到基础货币，返回 undefined
 */
function resolveTokenCurrency(code: string): CurrencyInfo | undefined {
  const baseCode = TOKEN_TO_BASE_RATE[code.toUpperCase()];
  if (baseCode) {
    return currencyMap.get(baseCode.toUpperCase());
  }
  return undefined;
}

/**
 * 获取货币符号
 * 支持复合代币码（如 ETHUSDT → ₮, BSCUSDC → USDC）
 */
export function getCurrencySymbol(code: string): string {
  const currency = getCurrencyByCode(code);
  if (currency) return currency.symbol;

  // 尝试通过 TOKEN_TO_BASE_RATE 解析复合代币码
  const baseCurrency = resolveTokenCurrency(code);
  if (baseCurrency) return baseCurrency.symbol;

  return code;
}

/**
 * 获取货币精度
 * 支持复合代币码（如 ETHUSDT → 6, BSCUSDT → 18）
 */
export function getCurrencyDecimals(code: string): number {
  const currency = getCurrencyByCode(code);
  if (currency) return currency.decimals;

  // 尝试通过 TOKEN_TO_BASE_RATE 解析复合代币码
  const baseCurrency = resolveTokenCurrency(code);
  if (baseCurrency) return baseCurrency.decimals;

  // 默认精度
  return isCryptoCurrency(code) ? 8 : 2;
}

/**
 * 判断是否为加密货币
 * 支持复合代币码（如 ETHUSDT → true）
 */
export function isCryptoCurrency(code: string): boolean {
  const currency = getCurrencyByCode(code);
  if (currency) return currency.type === 'crypto';

  // 复合代币码都是加密货币
  if (TOKEN_TO_BASE_RATE[code.toUpperCase()]) return true;

  return false;
}

/**
 * 判断是否为法币
 */
export function isFiatCurrency(code: string): boolean {
  const currency = getCurrencyByCode(code);
  if (currency) return currency.type === 'fiat';

  // 复合代币码不是法币
  if (TOKEN_TO_BASE_RATE[code.toUpperCase()]) return false;

  return false;
}

/**
 * 链上代币到基础汇率符号的映射
 * 从 TOKENS 自动推导（id !== token 的代币，如 ETHUSDT → USDT）
 * 用于汇率查询和作为未注册代币码的 fallback
 */
const TOKEN_TO_BASE_RATE: Record<string, string> = {};
// 从 TOKENS 自动推导
TOKENS.forEach(t => {
  if (t.id.toUpperCase() !== t.token.toUpperCase()) {
    TOKEN_TO_BASE_RATE[t.id.toUpperCase()] = t.token.toUpperCase();
  }
});
// 不在 TOKENS 中但需要汇率映射的代币
TOKEN_TO_BASE_RATE['CFXUSDT'] = 'USDT';
TOKEN_TO_BASE_RATE['CFXUSDC'] = 'USDC';
TOKEN_TO_BASE_RATE['MATICMBZ'] = 'MBZ';

/**
 * 获取基础汇率符号
 * 用于将链上代币映射到其基础符号以获取汇率
 */
export function getBaseRateSymbol(code: string): string {
  const upperCode = code.toUpperCase();
  return TOKEN_TO_BASE_RATE[upperCode] || upperCode;
}

/**
 * 获取常用货币列表 (用于 UI 选择器)
 */
export function getPopularCurrencies(): CurrencyInfo[] {
  const popularCodes = ['USD', 'EUR', 'CNY', 'GBP', 'JPY', 'BTC', 'ETH', 'USDT'];
  return popularCodes
    .map(code => getCurrencyByCode(code))
    .filter((c): c is CurrencyInfo => c !== undefined);
}

/**
 * 获取本地化的货币显示名称
 * 法币使用 Intl.DisplayNames API 获取本地化名称
 * 加密货币使用原始英文名称（全球通用）
 *
 * @param code 货币代码 (如 'USD', 'BTC')
 * @param locale 语言代码 (如 'en', 'zh', 'ja')
 * @returns 本地化的货币名称（纯文字，不含国旗 emoji）
 */
export function getCurrencyDisplayName(code: string, locale: string): string {
  const currency = getCurrencyByCode(code);

  // 加密货币使用原始英文名称（全球通用）
  if (currency?.type === 'crypto') {
    return currency.name;
  }

  // 法币使用 Intl.DisplayNames 获取本地化名称
  try {
    const displayNames = new Intl.DisplayNames([locale], { type: 'currency' });
    const localizedName = displayNames.of(code);
    if (localizedName) {
      return localizedName;
    }
  } catch {
    // Intl.DisplayNames 不可用时 fallback 到原始名称
  }

  // fallback: 去掉原始名称中的 emoji 前缀，只返回文字部分
  const nameStr = currency?.name || code;
  const spaceIndex = nameStr.indexOf(' ');
  if (spaceIndex > 0) {
    const prefix = nameStr.slice(0, spaceIndex);
    // 如果前缀不含 ASCII 字母，说明是 emoji 前缀
    if (!/[a-zA-Z]/.test(prefix)) {
      return nameStr.slice(spaceIndex + 1);
    }
  }
  return nameStr;
}

/**
 * 从货币代码生成国旗 emoji
 * 大多数法币代码的前两位字母对应 ISO 3166 国家代码
 * 某些国旗在部分系统上不可渲染（如 macOS 中国区的 🇹🇼），需要 UI 层处理 fallback
 */
const PROBLEMATIC_FLAG_CODES = new Set(['TWD']);

export function getCurrencyFlag(code: string): string | null {
  const currency = getCurrencyByCode(code);
  if (!currency || currency.type === 'crypto') return null;

  // 特殊处理：EUR 没有单一国家
  if (code === 'EUR') return '🇪🇺';
  // XAF, XOF 等特殊货币没有对应国旗
  if (code.startsWith('X')) return null;
  // 跳过已知不可渲染的国旗
  if (PROBLEMATIC_FLAG_CODES.has(code)) return null;

  // 从货币代码前两位生成国旗 emoji
  const countryCode = code.slice(0, 2).toUpperCase();
  try {
    return String.fromCodePoint(...countryCode.split('').map(c => 0x1f1e6 + c.charCodeAt(0) - 65));
  } catch {
    return null;
  }
}
