/**
 * AUTO-GENERATED by scripts/gen-api-paths.mjs — DO NOT EDIT
 *
 * Source: packages/core/api-spec/openapi.json (merged OpenAPI spec)
 * Re-run: pnpm --filter @mobazha/core generate:api
 *
 * Path functions accept RAW (unencoded) param values.
 * encodeURIComponent is applied internally — do NOT pre-encode.
 */

export const HOSTING_API_PATHS = {
  ACCOUNTS_LINK_CALLBACK: '/platform/v1/accounts/link-callback',
  ACCOUNTS_LINK_CONFIG: '/platform/v1/accounts/link/config',
  ACCOUNTS_LINK_TELEGRAM: '/platform/v1/accounts/link/telegram',
  ACCOUNTS_LINK_URL: '/platform/v1/accounts/link-url',
  ACCOUNTS_LINKED: '/platform/v1/accounts/linked',
  ACCOUNTS_ME: '/platform/v1/accounts/me',
  ACCOUNTS_MERGE: '/platform/v1/accounts/merge',
  ACCOUNTS_MERGE_PREVIEW: '/platform/v1/accounts/merge/preview',
  ACCOUNTS_PLAN: '/platform/v1/accounts/plan',
  ACCOUNTS_UNLINK: '/platform/v1/accounts/unlink',
  ADMIN_AI_CONFIG: '/platform/v1/admin/ai/config',
  ADMIN_CONFIG: '/platform/v1/admin/config',
  ADMIN_EXCHANGE_RATES_CONFIG: '/platform/v1/admin/exchange-rates/config',
  ADMIN_EXCHANGE_RATES_HEALTH: '/platform/v1/admin/exchange-rates/health',
  ADMIN_FIAT_PROVIDERS: '/platform/v1/admin/fiat-providers',
  ADMIN_FIAT_PROVIDERS_BY_PROVIDER: (provider: string) =>
    `/platform/v1/admin/fiat-providers/${encodeURIComponent(provider)}`,
  ADMIN_MODERATORS: '/platform/v1/admin/moderators',
  ADMIN_MODERATORS_BY_PEER_ID: (peerID: string) =>
    `/platform/v1/admin/moderators/${encodeURIComponent(peerID)}`,
  ADMIN_RELAY_CONFIG: '/platform/v1/admin/relay/config',
  ADMIN_MANAGED_ESCROW_CONFIG: '/platform/v1/admin/managed-escrow/config',
  ADMIN_SERVICES: '/platform/v1/admin/services',
  ADMIN_STATS: '/platform/v1/admin/stats',
  ADMIN_TENANTS: '/platform/v1/admin/tenants',
  ADMIN_TENANTS_ACTIVATE: (id: string) =>
    `/platform/v1/admin/tenants/${encodeURIComponent(id)}/activate`,
  ADMIN_TENANTS_ARCHIVE: (id: string) =>
    `/platform/v1/admin/tenants/${encodeURIComponent(id)}/archive`,
  ADMIN_TENANTS_BY_ID: (id: string) => `/platform/v1/admin/tenants/${encodeURIComponent(id)}`,
  ADMIN_TENANTS_EXPORT: (id: string) =>
    `/platform/v1/admin/tenants/${encodeURIComponent(id)}/export`,
  ADMIN_TENANTS_PLAN: (id: string) => `/platform/v1/admin/tenants/${encodeURIComponent(id)}/plan`,
  ADMIN_TENANTS_SUSPEND: (id: string) =>
    `/platform/v1/admin/tenants/${encodeURIComponent(id)}/suspend`,
  AUTH_CERTIFICATE: '/platform/v1/auth/certificate',
  AUTH_DISCORD_CHECK_USER: '/platform/v1/auth/discord/check-user',
  AUTH_DISCORD_MINI_APP_SIGNIN: '/platform/v1/auth/discord/mini-app-signin',
  AUTH_DISCORD_OAUTH_CALLBACK: '/platform/v1/auth/discord/oauth-callback',
  AUTH_DISCORD_OAUTH2_TOKEN: '/platform/v1/auth/discord/oauth2-token',
  AUTH_IDENTITY: '/platform/v1/auth/identity',
  AUTH_SCOPES: '/platform/v1/auth/scopes',
  AUTH_SIGNIN: '/platform/v1/auth/signin',
  AUTH_TELEGRAM_BIND_COMPLETE: '/platform/v1/auth/telegram/bind-complete',
  AUTH_TELEGRAM_BIND_RESULT: '/platform/v1/auth/telegram/bind-result',
  AUTH_TELEGRAM_BIND_START: '/platform/v1/auth/telegram/bind-start',
  AUTH_TELEGRAM_CHECK_MINI_APP_USER: '/platform/v1/auth/telegram/check-mini-app-user',
  AUTH_TELEGRAM_MINI_APP_SIGNIN: '/platform/v1/auth/telegram/mini-app-signin',
  AUTH_TELEGRAM_SIGNIN: '/platform/v1/auth/telegram/signin',
  AUTH_TOKENS: '/platform/v1/auth/tokens',
  AUTH_TOKENS_BY_TOKEN_ID: (tokenID: string) =>
    `/platform/v1/auth/tokens/${encodeURIComponent(tokenID)}`,
  COLLECTIBLES_HUB_INTAKE: '/platform/v1/collectibles/hub/intake',
  COLLECTIBLES_HUB_REDEMPTIONS: '/platform/v1/collectibles/hub/redemptions',
  COLLECTIBLES_HUB_SLOTS: '/platform/v1/collectibles/hub/slots',
  COLLECTIBLES_HUB_SLOTS_BY_ID: (id: string) =>
    `/platform/v1/collectibles/hub/slots/${encodeURIComponent(id)}`,
  COLLECTIBLES_HUB_SLOTS_MINT: (id: string) =>
    `/platform/v1/collectibles/hub/slots/${encodeURIComponent(id)}/mint`,
  COLLECTIBLES_HUB_SLOTS_REJECT: (id: string) =>
    `/platform/v1/collectibles/hub/slots/${encodeURIComponent(id)}/reject`,
  COLLECTIBLES_MY_SOURCE_DEPOSITS: '/platform/v1/collectibles/my/source-deposits',
  COLLECTIBLES_MY_SOURCE_DEPOSITS_SHIP: (id: string) =>
    `/platform/v1/collectibles/my/source-deposits/${encodeURIComponent(id)}/ship`,
  COLLECTIBLES_NFTS: '/platform/v1/collectibles/nfts',
  COLLECTIBLES_NFTS_BURN_TX: (mint: string) =>
    `/platform/v1/collectibles/nfts/${encodeURIComponent(mint)}/burn-tx`,
  COLLECTIBLES_NFTS_BY_MINT: (mint: string) =>
    `/platform/v1/collectibles/nfts/${encodeURIComponent(mint)}`,
  COLLECTIBLES_PRIMARY_SALES: '/platform/v1/collectibles/primary-sales',
  COLLECTIBLES_PRIMARY_SALES_BY_ID: (id: string) =>
    `/platform/v1/collectibles/primary-sales/${encodeURIComponent(id)}`,
  COLLECTIBLES_PRIMARY_SALES_BY_ORDER: (orderID: string) =>
    `/platform/v1/collectibles/primary-sales/by-order/${encodeURIComponent(orderID)}`,
  COLLECTIBLES_PRIMARY_SALES_NFT: (id: string) =>
    `/platform/v1/collectibles/primary-sales/${encodeURIComponent(id)}/nft`,
  COLLECTIBLES_PRIMARY_SALES_PAID: (id: string) =>
    `/platform/v1/collectibles/primary-sales/${encodeURIComponent(id)}/paid`,
  COLLECTIBLES_PRIMARY_SALES_RELEASE_QUEUE: '/platform/v1/collectibles/primary-sales/release-queue',
  COLLECTIBLES_PRIMARY_SALES_RELEASE_REQUEST: (id: string) =>
    `/platform/v1/collectibles/primary-sales/${encodeURIComponent(id)}/release-request`,
  COLLECTIBLES_PRIMARY_SALES_RELEASE_RESULT: (id: string) =>
    `/platform/v1/collectibles/primary-sales/${encodeURIComponent(id)}/release-result`,
  COLLECTIBLES_PRIMARY_SALES_RELEASE_RETRY: '/platform/v1/collectibles/primary-sales/release-retry',
  COLLECTIBLES_RECONCILE: '/platform/v1/collectibles/reconcile',
  COLLECTIBLES_RECONCILE_RECOVER_MINTS: '/platform/v1/collectibles/reconcile/recover-mints',
  COLLECTIBLES_REDEMPTIONS: '/platform/v1/collectibles/redemptions',
  COLLECTIBLES_REDEMPTIONS_BY_ID: (id: string) =>
    `/platform/v1/collectibles/redemptions/${encodeURIComponent(id)}`,
  COLLECTIBLES_REDEMPTIONS_SETTLE: (id: string) =>
    `/platform/v1/collectibles/redemptions/${encodeURIComponent(id)}/settle`,
  COLLECTIBLES_REDEMPTIONS_SHIP: (id: string) =>
    `/platform/v1/collectibles/redemptions/${encodeURIComponent(id)}/ship`,
  COLLECTIBLES_SOURCE_DEPOSITS: '/platform/v1/collectibles/source-deposits',
  COLLECTIBLES_SOURCE_DEPOSITS_APPROVE: (id: string) =>
    `/platform/v1/collectibles/source-deposits/${encodeURIComponent(id)}/approve`,
  COLLECTIBLES_SOURCE_DEPOSITS_BY_ID: (id: string) =>
    `/platform/v1/collectibles/source-deposits/${encodeURIComponent(id)}`,
  COLLECTIBLES_SOURCE_DEPOSITS_DEFAULT: (id: string) =>
    `/platform/v1/collectibles/source-deposits/${encodeURIComponent(id)}/default`,
  COLLECTIBLES_SOURCE_DEPOSITS_FIRST_SALE: (id: string) =>
    `/platform/v1/collectibles/source-deposits/${encodeURIComponent(id)}/first-sale`,
  COLLECTIBLES_SOURCE_DEPOSITS_MINT: (id: string) =>
    `/platform/v1/collectibles/source-deposits/${encodeURIComponent(id)}/mint`,
  COLLECTIBLES_SOURCE_DEPOSITS_REJECT: (id: string) =>
    `/platform/v1/collectibles/source-deposits/${encodeURIComponent(id)}/reject`,
  COLLECTIBLES_SOURCE_DEPOSITS_SETTLE: (id: string) =>
    `/platform/v1/collectibles/source-deposits/${encodeURIComponent(id)}/settle`,
  COLLECTIBLES_SOURCE_DEPOSITS_SHIP: (id: string) =>
    `/platform/v1/collectibles/source-deposits/${encodeURIComponent(id)}/ship`,
  COLLECTIBLES_WALLETS: '/platform/v1/collectibles/wallets',
  COMMUNITY_MARKETPLACES_ADMIN_BANNERS: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/admin/banners`,
  COMMUNITY_MARKETPLACES_ADMIN_FEATURED: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/admin/featured`,
  COMMUNITY_MARKETPLACES_BANNERS: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/banners`,
  COMMUNITY_MARKETPLACES_BY_PLATFORM: (platform: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}`,
  COMMUNITY_MARKETPLACES_BY_PLATFORM_INSTANCE_ID: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}`,
  COMMUNITY_MARKETPLACES_CHECK_ADMIN: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/check-admin`,
  COMMUNITY_MARKETPLACES_DISCORD_VERIFY_MEMBER: (instanceID: string) =>
    `/platform/v1/community-marketplaces/discord/${encodeURIComponent(instanceID)}/verify-member`,
  COMMUNITY_MARKETPLACES_FEATURED: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/featured`,
  COMMUNITY_MARKETPLACES_GROUPS: '/platform/v1/community-marketplaces/groups',
  COMMUNITY_MARKETPLACES_LISTINGS: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/listings`,
  COMMUNITY_MARKETPLACES_PUBLIC: (identifier: string) =>
    `/platform/v1/community-marketplaces/public/${encodeURIComponent(identifier)}`,
  COMMUNITY_MARKETPLACES_PUBLIC_SELLER_APPLICATION: (identifier: string) =>
    `/platform/v1/community-marketplaces/public/${encodeURIComponent(identifier)}/seller-application`,
  COMMUNITY_MARKETPLACES_PUBLIC_SELLERS_APPLY: (identifier: string) =>
    `/platform/v1/community-marketplaces/public/${encodeURIComponent(identifier)}/sellers/apply`,
  COMMUNITY_MARKETPLACES_SEARCH: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/search`,
  COMMUNITY_MARKETPLACES_SELLERS: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/sellers`,
  COMMUNITY_MARKETPLACES_SELLERS_APPLY: (platform: string, instanceID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/sellers/apply`,
  COMMUNITY_MARKETPLACES_SELLERS_PRODUCT_GROUPS: (
    platform: string,
    instanceID: string,
    sellerID: string
  ) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/sellers/${encodeURIComponent(sellerID)}/product-groups`,
  COMMUNITY_MARKETPLACES_SELLERS_REVIEW: (platform: string, instanceID: string, sellerID: string) =>
    `/platform/v1/community-marketplaces/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}/sellers/${encodeURIComponent(sellerID)}/review`,
  COMMUNITY_MARKETPLACES_TELEGRAM_VERIFY_MEMBER: (instanceID: string) =>
    `/platform/v1/community-marketplaces/telegram/${encodeURIComponent(instanceID)}/verify-member`,
  ENCRYPTION_LISTINGS_KEY: (peerID: string, slug: string) =>
    `/platform/v1/encryption/listings/${encodeURIComponent(peerID)}/${encodeURIComponent(slug)}/key`,
  ENCRYPTION_PRODUCT_GROUPS_ROTATE_KEY: (id: string) =>
    `/platform/v1/encryption/product-groups/${encodeURIComponent(id)}/rotate-key`,
  ENCRYPTION_PROFILE_VISIBILITY: '/platform/v1/encryption/profile/visibility',
  ENCRYPTION_STORES_KEYS: (peerID: string) =>
    `/platform/v1/encryption/stores/${encodeURIComponent(peerID)}/keys`,
  ENCRYPTION_SYNC_LISTING_KEY: '/platform/v1/encryption/sync-listing-key',
  ENCRYPTION_SYNC_PRODUCT_GROUP_KEY: '/platform/v1/encryption/sync-product-group-key',
  EXCHANGE_RATES: '/platform/v1/exchange-rates',
  FEATURES: '/platform/v1/features',
  FEATURES_BY_KEY: (key: string) => `/platform/v1/features/${encodeURIComponent(key)}`,
  FIAT_PROVIDERS_CONNECTION: (providerID: string) =>
    `/platform/v1/fiat/providers/${encodeURIComponent(providerID)}/connection`,
  FIAT_PROVIDERS_ONBOARDING: (providerID: string) =>
    `/platform/v1/fiat/providers/${encodeURIComponent(providerID)}/onboarding`,
  FIAT_PROVIDERS_ONBOARDING_CALLBACK: (providerID: string) =>
    `/platform/v1/fiat/providers/${encodeURIComponent(providerID)}/onboarding/callback`,
  FIAT_PROVIDERS_STATUS: (providerID: string) =>
    `/platform/v1/fiat/providers/${encodeURIComponent(providerID)}/status`,
  INTEGRATIONS_TELEGRAM_WEBHOOK: '/platform/v1/integrations/telegram/webhook',
  INTEGRATIONS_TELEGRAM_WEBHOOK_BY_BOT_ID: (botID: string) =>
    `/platform/v1/integrations/telegram/webhook/${encodeURIComponent(botID)}`,
  IPNS: '/platform/v1/ipns',
  IPNS_BY_PEER_ID: (peerID: string) => `/platform/v1/ipns/${encodeURIComponent(peerID)}`,
  MARKETPLACE_MEMBERSHIPS_DECLINE: (marketplaceID: string) =>
    `/platform/v1/marketplace-memberships/${encodeURIComponent(marketplaceID)}/decline`,
  MARKETPLACE_MEMBERSHIPS_LEAVE: (marketplaceID: string) =>
    `/platform/v1/marketplace-memberships/${encodeURIComponent(marketplaceID)}/leave`,
  MARKETPLACE_MEMBERSHIPS_MINE: '/platform/v1/marketplace-memberships/mine',
  MARKETPLACE_MEMBERSHIPS_REVIEW_EVENTS: '/platform/v1/marketplace-memberships/review-events',
  MARKETPLACE_MEMBERSHIPS_REVIEW_EVENTS_BY_MARKETPLACE_ID: (marketplaceID: string) =>
    `/platform/v1/marketplace-memberships/${encodeURIComponent(marketplaceID)}/review-events`,
  MARKETPLACE_MEMBERSHIPS_REVIEW_EVENTS_READ: (marketplaceID: string, eventID: string) =>
    `/platform/v1/marketplace-memberships/${encodeURIComponent(marketplaceID)}/review-events/${encodeURIComponent(eventID)}/read`,
  MARKETPLACE_MEMBERSHIPS_REVIEW_EVENTS_READ_ALL:
    '/platform/v1/marketplace-memberships/review-events/read-all',
  MARKETPLACES: '/platform/v1/marketplaces',
  MARKETPLACES_ATTRIBUTION_SUMMARY: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/attribution-summary`,
  MARKETPLACES_BY_ID: (id: string) => `/platform/v1/marketplaces/${encodeURIComponent(id)}`,
  MARKETPLACES_CONFIG: (id: string) => `/platform/v1/marketplaces/${encodeURIComponent(id)}/config`,
  MARKETPLACES_CURATION_BY_ID: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/curation`,
  MARKETPLACES_CURATION_BY_ID_ITEM_ID: (id: string, itemID: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/curation/${encodeURIComponent(itemID)}`,
  MARKETPLACES_CURATION_CANDIDATES: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/curation/candidates`,
  MARKETPLACES_CURATION_REORDER: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/curation/reorder`,
  MARKETPLACES_DOMAINS_CUSTOM_VERIFY: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/domains/custom/verify`,
  MARKETPLACES_LINK: (id: string) => `/platform/v1/marketplaces/${encodeURIComponent(id)}/link`,
  MARKETPLACES_MINE: '/platform/v1/marketplaces/mine',
  MARKETPLACES_PREVIEW: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/preview`,
  MARKETPLACES_PUBLISH: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/publish`,
  MARKETPLACES_SELLER_REVIEW_EVENTS: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/seller-review-events`,
  MARKETPLACES_SELLERS_ACCEPT: (id: string, peerID: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/sellers/${encodeURIComponent(peerID)}/accept`,
  MARKETPLACES_SELLERS_BY_ID: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/sellers`,
  MARKETPLACES_SELLERS_BY_ID_PEER_ID: (id: string, peerID: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/sellers/${encodeURIComponent(peerID)}`,
  MARKETPLACES_SELLERS_INVITE: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/sellers/invite`,
  MARKETPLACES_SUSPEND: (id: string) =>
    `/platform/v1/marketplaces/${encodeURIComponent(id)}/suspend`,
  MATRIX_CONFIG: '/platform/v1/matrix/config',
  MATRIX_PEER_ID: '/platform/v1/matrix/peer-id',
  MATRIX_STORE_INVITE: '/platform/v1/matrix/store/invite',
  MATRIX_STORE_KICK: '/platform/v1/matrix/store/kick',
  MATRIX_STORE_SPACES: '/platform/v1/matrix/store/spaces',
  MODERATORS_RECOMMENDED: '/platform/v1/moderators/recommended',
  PRODUCT_GROUPS: '/platform/v1/product-groups',
  PRODUCT_GROUPS_AUTHORIZATIONS_BY_PRODUCT_GROUP_ID: (productGroupID: string) =>
    `/platform/v1/product-groups/${encodeURIComponent(productGroupID)}/authorizations`,
  PRODUCT_GROUPS_AUTHORIZATIONS_BY_PRODUCT_GROUP_ID_AUTH_ID: (
    productGroupID: string,
    authID: string
  ) =>
    `/platform/v1/product-groups/${encodeURIComponent(productGroupID)}/authorizations/${encodeURIComponent(authID)}`,
  PRODUCT_GROUPS_BY_GROUP_ID: (groupID: string) =>
    `/platform/v1/product-groups/${encodeURIComponent(groupID)}`,
  PRODUCT_GROUPS_ITEMS_BY_GROUP_ID: (groupID: string) =>
    `/platform/v1/product-groups/${encodeURIComponent(groupID)}/items`,
  PRODUCT_GROUPS_ITEMS_BY_GROUP_ID_SLUG: (groupID: string, slug: string) =>
    `/platform/v1/product-groups/${encodeURIComponent(groupID)}/items/${encodeURIComponent(slug)}`,
  PUBLIC_MARKETPLACES: '/platform/v1/public-marketplaces',
  PUBLIC_MARKETPLACES_ATTRIBUTION_EVENTS: (identifier: string) =>
    `/platform/v1/public-marketplaces/${encodeURIComponent(identifier)}/attribution-events`,
  PUBLIC_MARKETPLACES_BY_IDENTIFIER: (identifier: string) =>
    `/platform/v1/public-marketplaces/${encodeURIComponent(identifier)}`,
  PUBLIC_MARKETPLACES_SELLER_APPLICATIONS: (identifier: string) =>
    `/platform/v1/public-marketplaces/${encodeURIComponent(identifier)}/seller-applications`,
  PUBLIC_MARKETPLACES_SELLER_APPLICATIONS_MINE: (identifier: string) =>
    `/platform/v1/public-marketplaces/${encodeURIComponent(identifier)}/seller-applications/mine`,
  RELAY_EXECUTE: '/platform/v1/relay/execute',
  RELAY_GAS_WALLET: '/platform/v1/relay/gas-wallet',
  RELAY_GAS_WALLET_STATUS: '/platform/v1/relay/gas-wallet/status',
  RELAY_STATUS: '/platform/v1/relay/status',
  SELLERS_MARKETPLACES: (userID: string) =>
    `/platform/v1/sellers/${encodeURIComponent(userID)}/marketplaces`,
  SELLERS_VISIBILITY: (userID: string, platform: string, instanceID: string) =>
    `/platform/v1/sellers/${encodeURIComponent(userID)}/visibility/${encodeURIComponent(platform)}/${encodeURIComponent(instanceID)}`,
  SERVER_INFO: '/platform/v1/server/info',
  STORE_ACCESS_CHECK: '/platform/v1/store-access/check',
  STORE_ACCESS_LIST: '/platform/v1/store-access-list',
  STORE_ACCESS_REQUESTS: '/platform/v1/store-access-requests',
  STORE_ACCESS_REQUESTS_BY_REQUEST_ID: (requestID: string) =>
    `/platform/v1/store-access-requests/${encodeURIComponent(requestID)}`,
  STORE_ACCESS_SETTINGS: '/platform/v1/store-access-settings',
  STORE_BOTS: '/platform/v1/store-bots',
  STORE_BOTS_REPAIR_WEBHOOK: '/platform/v1/store-bots/repair-webhook',
  STORE_BOTS_SYNC_MENU_BUTTON: '/platform/v1/store-bots/sync-menu-button',
  STORE_BOTS_WEBHOOK_STATUS: '/platform/v1/store-bots/webhook-status',
  STORE_DOMAINS_CHECK: '/platform/v1/store-domains/check',
  STORE_LINKS: '/platform/v1/store-links',
  STORE_LINKS_REGENERATE: '/platform/v1/store-links/regenerate',
  STORE_LINKS_RESOLVE: '/platform/v1/store-links/resolve',
  STORE_LINKS_RESOLVE_BY_SHORT_CODE: (shortCode: string) =>
    `/platform/v1/store-links/resolve/${encodeURIComponent(shortCode)}`,
  STOREFRONTS_BY_SLUG: (slug: string) =>
    `/platform/v1/storefronts/by-slug/${encodeURIComponent(slug)}`,
  STORES_BIND_CALLBACK: '/platform/v1/stores/bind/callback',
  STORES_BIND_START: '/platform/v1/stores/bind/start',
  STORES_BIND_STATUS: '/platform/v1/stores/bind/status',
  STORES_CLAIM: '/platform/v1/stores/claim',
  STORES_CLAIM_BY_PEER_ID: (peerID: string) =>
    `/platform/v1/stores/${encodeURIComponent(peerID)}/claim`,
  STORES_DOMAIN: (peerID: string) => `/platform/v1/stores/${encodeURIComponent(peerID)}/domain`,
  STORES_HEARTBEAT: '/platform/v1/stores/heartbeat',
  STORES_MATRIX_PROVISION: (peerID: string) =>
    `/platform/v1/stores/${encodeURIComponent(peerID)}/matrix/provision`,
  STORES_MY: '/platform/v1/stores/my',
  STORES_MY_STORES: '/platform/v1/stores/my-stores',
  STORES_OWNER_REPUTATION: '/platform/v1/stores/owner-reputation',
  STORES_REGISTER: '/platform/v1/stores/register',
  STORES_STATUS: (peerID: string) => `/platform/v1/stores/${encodeURIComponent(peerID)}/status`,
  STORES_STOREFRONTS_BY_PEER_ID: (peerID: string) =>
    `/platform/v1/stores/${encodeURIComponent(peerID)}/storefronts`,
  STORES_STOREFRONTS_BY_PEER_ID_SF_ID: (peerID: string, sfID: string) =>
    `/platform/v1/stores/${encodeURIComponent(peerID)}/storefronts/${encodeURIComponent(sfID)}`,
  STREAM_AUTH: '/platform/v1/stream/auth',
  SYSTEM_HUMA_PING: '/platform/v1/system/huma-ping',
  SYSTEM_HUMA_PING_AUTH: '/platform/v1/system/huma-ping-auth',
  USER_GROUPS: '/platform/v1/user-groups',
  USER_GROUPS_BY_GROUP_ID: (groupID: string) =>
    `/platform/v1/user-groups/${encodeURIComponent(groupID)}`,
  USER_GROUPS_MEMBERS_BATCH: (groupID: string) =>
    `/platform/v1/user-groups/${encodeURIComponent(groupID)}/members/batch`,
  USER_GROUPS_MEMBERS_BY_GROUP_ID: (groupID: string) =>
    `/platform/v1/user-groups/${encodeURIComponent(groupID)}/members`,
  USER_GROUPS_MEMBERS_BY_GROUP_ID_MEMBER_ID: (groupID: string, memberID: string) =>
    `/platform/v1/user-groups/${encodeURIComponent(groupID)}/members/${encodeURIComponent(memberID)}`,
} as const;

export const SEARCH_API_PATHS = {
  ACCESS_CHECK_LISTING: '/search/v1/access/check-listing',
  APP_LINKS: '/search/v1/app-links',
  BANNED_NODES: '/search/v1/banned-nodes',
  CONFIG: '/search/v1/config',
  CONTACT: '/search/v1/contact',
  EXTENSIONS_DOWNLOAD: '/search/v1/extensions/download',
  EXTENSIONS_LIST: '/search/v1/extensions/list',
  FILTERS_CONDITIONS: '/search/v1/filters/conditions',
  FILTERS_COUNTRIES: '/search/v1/filters/countries',
  FILTERS_MODERATORS: '/search/v1/filters/moderators',
  FILTERS_PROTECTED: '/search/v1/filters/protected',
  FILTERS_RATINGS: '/search/v1/filters/ratings',
  FILTERS_TYPES: '/search/v1/filters/types',
  LISTINGS: '/search/v1/listings',
  LISTINGS_BY_HASH: (hash: string) => `/search/v1/listings/${encodeURIComponent(hash)}`,
  LISTINGS_FRESH: '/search/v1/listings/fresh',
  LISTINGS_HOT: '/search/v1/listings/hot',
  LISTINGS_SHIPPINGS: (hash: string) => `/search/v1/listings/${encodeURIComponent(hash)}/shippings`,
  MEDIA_FILES: (hash: string) => `/search/v1/media/files/${encodeURIComponent(hash)}`,
  MEDIA_IMAGES: (hash: string) => `/search/v1/media/images/${encodeURIComponent(hash)}`,
  MODERATORS_VERIFIED: '/search/v1/moderators/verified',
  NETDB_FOLLOWERS: '/search/v1/netdb/followers',
  NETDB_FOLLOWERS_BY_PEER_ID: (peerID: string) =>
    `/search/v1/netdb/followers/${encodeURIComponent(peerID)}`,
  NETDB_FOLLOWING: '/search/v1/netdb/following',
  NETDB_FOLLOWING_BY_PEER_ID: (peerID: string) =>
    `/search/v1/netdb/following/${encodeURIComponent(peerID)}`,
  NETDB_LISTING_INDEXES: '/search/v1/netdb/listing-indexes',
  NETDB_LISTING_INDEXES_BY_PEER_ID: (peerID: string) =>
    `/search/v1/netdb/listing-indexes/${encodeURIComponent(peerID)}`,
  NETDB_LISTINGS: '/search/v1/netdb/listings',
  NETDB_LISTINGS_BY_ID: (id: string) => `/search/v1/netdb/listings/${encodeURIComponent(id)}`,
  NETDB_LISTINGS_BY_ID_SLUG: (id: string, slug: string) =>
    `/search/v1/netdb/listings/${encodeURIComponent(id)}/${encodeURIComponent(slug)}`,
  NETDB_LISTINGS_BY_LISTING_ID: (listingID: string) =>
    `/search/v1/netdb/listings/${encodeURIComponent(listingID)}`,
  NETDB_PROFILES: '/search/v1/netdb/profiles',
  NETDB_PROFILES_BY_PEER_ID: (peerID: string) =>
    `/search/v1/netdb/profiles/${encodeURIComponent(peerID)}`,
  NETDB_RATING_INDEXES: '/search/v1/netdb/rating-indexes',
  NETDB_RATING_INDEXES_BY_PEER_ID: (peerID: string) =>
    `/search/v1/netdb/rating-indexes/${encodeURIComponent(peerID)}`,
  NETDB_RATINGS: '/search/v1/netdb/ratings',
  NETDB_STORE_METADATA: '/search/v1/netdb/store-metadata',
  PROFILES: '/search/v1/profiles',
  PROFILES_BY_PEER_ID: (peerID: string) => `/search/v1/profiles/${encodeURIComponent(peerID)}`,
  PROFILES_CONNECTIONS: (peerID: string) =>
    `/search/v1/profiles/${encodeURIComponent(peerID)}/connections`,
  PROFILES_CONTACTS: (peerID: string) =>
    `/search/v1/profiles/${encodeURIComponent(peerID)}/contacts`,
  PROFILES_FOLLOWERS: (peerID: string) =>
    `/search/v1/profiles/${encodeURIComponent(peerID)}/followers`,
  PROFILES_FOLLOWING: (peerID: string) =>
    `/search/v1/profiles/${encodeURIComponent(peerID)}/following`,
  PROFILES_LISTINGS: (peerID: string) =>
    `/search/v1/profiles/${encodeURIComponent(peerID)}/listings`,
  PROFILES_POSTS: (peerID: string) => `/search/v1/profiles/${encodeURIComponent(peerID)}/posts`,
  PROFILES_RATINGS: (peerID: string) => `/search/v1/profiles/${encodeURIComponent(peerID)}/ratings`,
  PROFILES_RAW: (peerID: string) => `/search/v1/profiles/${encodeURIComponent(peerID)}/raw`,
  REPORTS: '/search/v1/reports',
  SEARCH: '/search/v1/search',
  SORTS: '/search/v1/sorts',
  STORES_METADATA: (peerID: string) => `/search/v1/stores/${encodeURIComponent(peerID)}/metadata`,
  SUBSCRIBE: '/search/v1/subscribe',
  SYNC_LISTING_AUTHORIZATIONS: '/search/v1/sync/listing-authorizations',
  SYNC_PRODUCT_GROUP_ITEMS: '/search/v1/sync/product-group-items',
  SYNC_STORE_ACCESS: '/search/v1/sync/store-access',
  SYNC_USER_GROUP_MEMBERS: '/search/v1/sync/user-group-members',
} as const;

export const NODE_API_PATHS = {
  ADMIN_PASSWORD: '/admin/password',
  ADMIN_VERSION: '/admin/version',
  AGENT_APPROVALS: '/agent/approvals',
  AGENT_APPROVALS_APPLY: (approvalId: string) =>
    `/agent/approvals/${encodeURIComponent(approvalId)}/apply`,
  AGENT_APPROVALS_BY_APPROVAL_ID: (approvalId: string) =>
    `/agent/approvals/${encodeURIComponent(approvalId)}`,
  AGENT_APPROVALS_DECISION: (approvalId: string) =>
    `/agent/approvals/${encodeURIComponent(approvalId)}/decision`,
  AGENT_ARTIFACTS: '/agent/artifacts',
  AGENT_ARTIFACTS_APPROVAL: (artifactId: string) =>
    `/agent/artifacts/${encodeURIComponent(artifactId)}/approval`,
  AGENT_ARTIFACTS_BY_ARTIFACT_ID: (artifactId: string) =>
    `/agent/artifacts/${encodeURIComponent(artifactId)}`,
  AGENT_ARTIFACTS_CONTENT: (artifactId: string) =>
    `/agent/artifacts/${encodeURIComponent(artifactId)}/content`,
  AGENT_ATTACHMENTS_ANALYZE: '/agent/attachments/analyze',
  AGENT_CHAT: '/agent/chat',
  AGENT_CHAT_BY_SESSION_ID: (sessionId: string) => `/agent/chat/${encodeURIComponent(sessionId)}`,
  AGENT_CHAT_SESSIONS: '/agent/chat/sessions',
  AGENT_MEMORIES: '/agent/memories',
  AGENT_MEMORIES_BY_MEMORY_ID: (memoryId: string) =>
    `/agent/memories/${encodeURIComponent(memoryId)}`,
  AGENT_PRODUCT_IMPORT_INGEST: '/agent/product-import/ingest',
  AGENT_PRODUCT_IMPORT_RUNS_ADVANCE: (runId: string) =>
    `/agent/product-import/runs/${encodeURIComponent(runId)}/advance`,
  AGENT_PRODUCT_IMPORT_RUNS_APPROVAL_APPLICATIONS: (runId: string) =>
    `/agent/product-import/runs/${encodeURIComponent(runId)}/approval-applications`,
  AGENT_PRODUCT_IMPORT_RUNS_APPROVAL_DECISIONS: (runId: string) =>
    `/agent/product-import/runs/${encodeURIComponent(runId)}/approval-decisions`,
  AGENT_PRODUCT_IMPORT_RUNS_APPROVALS: (runId: string) =>
    `/agent/product-import/runs/${encodeURIComponent(runId)}/approvals`,
  AGENT_PRODUCT_IMPORT_RUNS_WORKBENCH: (runId: string) =>
    `/agent/product-import/runs/${encodeURIComponent(runId)}/workbench`,
  AGENT_SKILL_RUNS: '/agent/skill-runs',
  AGENT_SKILL_RUNS_BY_RUN_ID: (runId: string) => `/agent/skill-runs/${encodeURIComponent(runId)}`,
  AI_GENERATE: '/ai/generate',
  AI_STATUS: '/ai/status',
  ANALYTICS_EVENTS: (peerID: string) => `/analytics/${encodeURIComponent(peerID)}/events`,
  ANALYTICS_STATS: '/analytics/stats',
  AUTH_IDENTITY: '/auth/identity',
  AUTH_SCOPES: '/auth/scopes',
  AUTH_TOKENS: '/auth/tokens',
  AUTH_TOKENS_BY_TOKEN_ID: (tokenID: string) => `/auth/tokens/${encodeURIComponent(tokenID)}`,
  BLOCKLIST: (peerID: string) => `/blocklist/${encodeURIComponent(peerID)}`,
  CARTS: '/carts',
  CARTS_COUNT: '/carts/count',
  CARTS_ITEMS: (peerID: string) => `/carts/${encodeURIComponent(peerID)}/items`,
  CASES: '/cases',
  CASES_BY_ORDER_ID: (orderID: string) => `/cases/${encodeURIComponent(orderID)}`,
  CHAT_BLOCKED_USERS: '/chat/blocked-users',
  CHAT_INVITES: '/chat/invites',
  CHAT_MEDIA: (serverName: string, mediaID: string) =>
    `/chat/media/${encodeURIComponent(serverName)}/${encodeURIComponent(mediaID)}`,
  CHAT_MEDIA_UPLOAD: '/chat/media/upload',
  CHAT_PRESENCE: '/chat/presence',
  CHAT_ROOMS: '/chat/rooms',
  CHAT_ROOMS_AVATAR: (roomID: string) => `/chat/rooms/${encodeURIComponent(roomID)}/avatar`,
  CHAT_ROOMS_INVITE: (roomID: string) => `/chat/rooms/${encodeURIComponent(roomID)}/invite`,
  CHAT_ROOMS_JOIN: (roomID: string) => `/chat/rooms/${encodeURIComponent(roomID)}/join`,
  CHAT_ROOMS_KICK: (roomID: string) => `/chat/rooms/${encodeURIComponent(roomID)}/kick`,
  CHAT_ROOMS_LEAVE: (roomID: string) => `/chat/rooms/${encodeURIComponent(roomID)}/leave`,
  CHAT_ROOMS_MEMBERS: (roomID: string) => `/chat/rooms/${encodeURIComponent(roomID)}/members`,
  CHAT_ROOMS_MESSAGES_BY_ROOM_ID: (roomID: string) =>
    `/chat/rooms/${encodeURIComponent(roomID)}/messages`,
  CHAT_ROOMS_MESSAGES_BY_ROOM_ID_EVENT_ID: (roomID: string, eventID: string) =>
    `/chat/rooms/${encodeURIComponent(roomID)}/messages/${encodeURIComponent(eventID)}`,
  CHAT_ROOMS_MESSAGES_REACTIONS: (roomID: string, eventID: string) =>
    `/chat/rooms/${encodeURIComponent(roomID)}/messages/${encodeURIComponent(eventID)}/reactions`,
  CHAT_ROOMS_READ: (roomID: string) => `/chat/rooms/${encodeURIComponent(roomID)}/read`,
  CHAT_ROOMS_SETTINGS: (roomID: string) => `/chat/rooms/${encodeURIComponent(roomID)}/settings`,
  CHAT_ROOMS_TYPING: (roomID: string) => `/chat/rooms/${encodeURIComponent(roomID)}/typing`,
  CHAT_SETTINGS: '/chat/settings',
  CHAT_STATUS: '/chat/status',
  CHAT_USERS_BLOCK: (userID: string) => `/chat/users/${encodeURIComponent(userID)}/block`,
  CHAT_VERIFICATION_ACCEPT: (txnId: string) =>
    `/chat/verification/${encodeURIComponent(txnId)}/accept`,
  CHAT_VERIFICATION_CANCEL: (txnId: string) =>
    `/chat/verification/${encodeURIComponent(txnId)}/cancel`,
  CHAT_VERIFICATION_CONFIRM: (txnId: string) =>
    `/chat/verification/${encodeURIComponent(txnId)}/confirm`,
  CHAT_VERIFICATION_REQUEST: '/chat/verification/request',
  CHAT_VERIFICATION_START_SAS: (txnId: string) =>
    `/chat/verification/${encodeURIComponent(txnId)}/start-sas`,
  COLLECTIONS: '/collections',
  COLLECTIONS_BY_COLLECTION_ID: (collectionID: string) =>
    `/collections/${encodeURIComponent(collectionID)}`,
  COLLECTIONS_PRODUCTS_BY_COLLECTION_ID: (collectionID: string) =>
    `/collections/${encodeURIComponent(collectionID)}/products`,
  COLLECTIONS_PRODUCTS_BY_COLLECTION_ID_SLUG: (collectionID: string, slug: string) =>
    `/collections/${encodeURIComponent(collectionID)}/products/${encodeURIComponent(slug)}`,
  COLLECTIONS_PRODUCTS_REORDER: (collectionID: string) =>
    `/collections/${encodeURIComponent(collectionID)}/products/reorder`,
  COLLECTIONS_PUBLISHED_BY_PEER_ID: (peerID: string) =>
    `/collections/${encodeURIComponent(peerID)}/published`,
  COLLECTIONS_PUBLISHED_BY_PEER_ID_COLLECTION_ID: (peerID: string, collectionID: string) =>
    `/collections/${encodeURIComponent(peerID)}/published/${encodeURIComponent(collectionID)}`,
  CONFIG: '/config',
  CRYPTO_HASH: '/crypto/hash',
  CRYPTO_SIGN: '/crypto/sign',
  CRYPTO_VERIFY: '/crypto/verify',
  DIGITAL_ASSETS: '/digital-assets',
  DIGITAL_ASSETS_BY_ASSET_ID: (assetID: string) => `/digital-assets/${encodeURIComponent(assetID)}`,
  DIGITAL_ASSETS_LICENSE_KEY: '/digital-assets/license-key',
  DIGITAL_ASSETS_LICENSE_KEYS: '/digital-assets/license-keys',
  DIGITAL_ASSETS_LICENSE_KEYS_REVOKE: (keyID: string) =>
    `/digital-assets/license-keys/${encodeURIComponent(keyID)}/revoke`,
  DIGITAL_ASSETS_LICENSE_KEYS_STATS: '/digital-assets/license-keys/stats',
  DIGITAL_ASSETS_LINK: '/digital-assets/link',
  DISCOUNTS: '/discounts',
  DISCOUNTS_APPLICABLE: (peerID: string) => `/discounts/${encodeURIComponent(peerID)}/applicable`,
  DISCOUNTS_BY_DISCOUNT_ID: (discountID: string) => `/discounts/${encodeURIComponent(discountID)}`,
  DISCOUNTS_CALCULATE: (peerID: string) => `/discounts/${encodeURIComponent(peerID)}/calculate`,
  DISCOUNTS_CODES_BY_DISCOUNT_ID: (discountID: string) =>
    `/discounts/${encodeURIComponent(discountID)}/codes`,
  DISCOUNTS_CODES_BY_DISCOUNT_ID_CODE_ID: (discountID: string, codeID: string) =>
    `/discounts/${encodeURIComponent(discountID)}/codes/${encodeURIComponent(codeID)}`,
  DISCOUNTS_REDEMPTIONS: (discountID: string) =>
    `/discounts/${encodeURIComponent(discountID)}/redemptions`,
  DISCOUNTS_VALIDATE: (peerID: string) => `/discounts/${encodeURIComponent(peerID)}/validate`,
  DISPUTES_AFTER_SALE: (orderID: string) => `/disputes/${encodeURIComponent(orderID)}/after-sale`,
  DISPUTES_CLOSE: (orderID: string) => `/disputes/${encodeURIComponent(orderID)}/close`,
  DISPUTES_INSTRUCTIONS_RELEASE: (orderID: string) =>
    `/disputes/${encodeURIComponent(orderID)}/instructions/release`,
  DISPUTES_OPEN: (orderID: string) => `/disputes/${encodeURIComponent(orderID)}/open`,
  DISPUTES_RELEASE: (orderID: string) => `/disputes/${encodeURIComponent(orderID)}/release`,
  DISPUTES_RELEASE_AFTER_TIMEOUT: (orderID: string) =>
    `/disputes/${encodeURIComponent(orderID)}/release-after-timeout`,
  EXCHANGE_RATES: '/exchange-rates',
  EXCHANGE_RATES_BY_CURRENCY_CODE: (currencyCode: string) =>
    `/exchange-rates/${encodeURIComponent(currencyCode)}`,
  FEATURES: '/features',
  FIAT_CONFIG: (providerID: string) => `/fiat/${encodeURIComponent(providerID)}/config`,
  FIAT_PAYMENTS_BY_PEER_ID_PROVIDER_ID: (peerID: string, providerID: string) =>
    `/fiat/${encodeURIComponent(peerID)}/${encodeURIComponent(providerID)}/payments`,
  FIAT_PAYMENTS_BY_PROVIDER_ID: (providerID: string) =>
    `/fiat/${encodeURIComponent(providerID)}/payments`,
  FIAT_PAYMENTS_BY_PROVIDER_ID_PAYMENT_ID: (providerID: string, paymentID: string) =>
    `/fiat/${encodeURIComponent(providerID)}/payments/${encodeURIComponent(paymentID)}`,
  FIAT_PAYMENTS_CAPTURE_BY_PEER_ID_PROVIDER_ID_SESSION_ID: (
    peerID: string,
    providerID: string,
    sessionID: string
  ) =>
    `/fiat/${encodeURIComponent(peerID)}/${encodeURIComponent(providerID)}/payments/${encodeURIComponent(sessionID)}/capture`,
  FIAT_PAYMENTS_CAPTURE_BY_PROVIDER_ID_SESSION_ID: (providerID: string, sessionID: string) =>
    `/fiat/${encodeURIComponent(providerID)}/payments/${encodeURIComponent(sessionID)}/capture`,
  FIAT_PAYMENTS_REFUND: (providerID: string, paymentID: string) =>
    `/fiat/${encodeURIComponent(providerID)}/payments/${encodeURIComponent(paymentID)}/refund`,
  FIAT_PROVIDERS: '/fiat/providers',
  FIAT_PROVIDERS_BY_PEER_ID: (peerID: string) => `/fiat/${encodeURIComponent(peerID)}/providers`,
  FIAT_SETUP_WEBHOOK: (providerID: string) =>
    `/fiat/${encodeURIComponent(providerID)}/setup-webhook`,
  FIAT_STATUS: (providerID: string) => `/fiat/${encodeURIComponent(providerID)}/status`,
  FIAT_VERIFY: (providerID: string) => `/fiat/${encodeURIComponent(providerID)}/verify`,
  FIAT_WEBHOOKS: (providerID: string) => `/fiat/${encodeURIComponent(providerID)}/webhooks`,
  FOLLOWERS: '/followers',
  FOLLOWERS_BY_PEER_ID: (peerID: string) => `/followers/${encodeURIComponent(peerID)}`,
  FOLLOWERS_CHECK: (peerID: string) => `/followers/${encodeURIComponent(peerID)}/check`,
  FOLLOWING: '/following',
  FOLLOWING_BY_PEER_ID: (peerID: string) => `/following/${encodeURIComponent(peerID)}`,
  FULFILLMENT_ALERTS: '/fulfillment/alerts',
  FULFILLMENT_ALERTS_BY_ALERT_ID: (alertID: string) =>
    `/fulfillment/alerts/${encodeURIComponent(alertID)}`,
  FULFILLMENT_CATALOG_BY_PROVIDER_ID: (providerID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/catalog`,
  FULFILLMENT_CATALOG_BY_PROVIDER_ID_PRODUCT_ID: (providerID: string, productID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/catalog/${encodeURIComponent(productID)}`,
  FULFILLMENT_CONNECT: (providerID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/connect`,
  FULFILLMENT_DISCONNECT: (providerID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/disconnect`,
  FULFILLMENT_IMPORT: (providerID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/import`,
  FULFILLMENT_LOCATIONS: '/fulfillment/locations',
  FULFILLMENT_LOCATIONS_BY_LOCATION_ID: (locationID: string) =>
    `/fulfillment/locations/${encodeURIComponent(locationID)}`,
  FULFILLMENT_ORDERS_STATUS: (orderID: string) =>
    `/fulfillment/orders/${encodeURIComponent(orderID)}/status`,
  FULFILLMENT_PRODUCTS_SYNC: (slug: string) =>
    `/fulfillment/products/${encodeURIComponent(slug)}/sync`,
  FULFILLMENT_PROVIDERS: '/fulfillment/providers',
  FULFILLMENT_RULES: '/fulfillment/rules',
  FULFILLMENT_RULES_BY_RULE_ID: (ruleID: string) =>
    `/fulfillment/rules/${encodeURIComponent(ruleID)}`,
  FULFILLMENT_SHIPPING_ESTIMATES: (providerID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/shipping-estimates`,
  FULFILLMENT_STATUS: (providerID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/status`,
  FULFILLMENT_STORE_PRODUCTS_BY_PROVIDER_ID: (providerID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/store-products`,
  FULFILLMENT_STORE_PRODUCTS_BY_PROVIDER_ID_SYNC_PRODUCT_ID: (
    providerID: string,
    syncProductID: string
  ) =>
    `/fulfillment/${encodeURIComponent(providerID)}/store-products/${encodeURIComponent(syncProductID)}`,
  FULFILLMENT_SYNCED_PRODUCTS_BY_PROVIDER_ID: (providerID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/synced-products`,
  FULFILLMENT_SYNCED_PRODUCTS_BY_PROVIDER_ID_MAPPING_ID: (providerID: string, mappingID: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/synced-products/${encodeURIComponent(mappingID)}`,
  FULFILLMENT_WEBHOOKS: (providerID: string, webhookSecret: string) =>
    `/fulfillment/${encodeURIComponent(providerID)}/webhooks/${encodeURIComponent(webhookSecret)}`,
  GUEST_ORDERS: '/guest/orders',
  GUEST_ORDERS_BY_TOKEN: (token: string) => `/guest/orders/${encodeURIComponent(token)}`,
  GUEST_ORDERS_COMPLETE: (token: string) => `/guest/orders/${encodeURIComponent(token)}/complete`,
  GUEST_ORDERS_DETAIL: (token: string) => `/guest/orders/${encodeURIComponent(token)}/detail`,
  GUEST_ORDERS_QUOTE: '/guest/orders/quote',
  GUEST_ORDERS_SHIP: (token: string) => `/guest/orders/${encodeURIComponent(token)}/ship`,
  LISTINGS: '/listings',
  LISTINGS_BY_LISTING_ID: (listingID: string) => `/listings/${encodeURIComponent(listingID)}`,
  LISTINGS_BY_PEER_ID_SLUG: (peerID: string, slug: string) =>
    `/listings/${encodeURIComponent(peerID)}/${encodeURIComponent(slug)}`,
  LISTINGS_BY_SLUG: (slug: string) => `/listings/${encodeURIComponent(slug)}`,
  LISTINGS_IMPORT: '/listings/import',
  LISTINGS_IMPORT_GUMROAD: '/listings/import/gumroad',
  LISTINGS_IMPORT_JSON: '/listings/import/json',
  LISTINGS_INDEX: '/listings/index',
  LISTINGS_INDEX_BY_PEER_ID: (peerID: string) => `/listings/index/${encodeURIComponent(peerID)}`,
  LISTINGS_MINE: (slugOrCID: string) => `/listings/mine/${encodeURIComponent(slugOrCID)}`,
  LISTINGS_SUPPLY_SUMMARY: '/listings/supply-summary',
  LISTINGS_TEMPLATE: '/listings/template',
  MEDIA_AVATAR: '/media/avatar',
  MEDIA_FILES: '/media/files',
  MEDIA_FILES_BY_FILE_ID: (fileID: string) => `/media/files/${encodeURIComponent(fileID)}`,
  MEDIA_HEADER: '/media/header',
  MEDIA_IMAGES: '/media/images',
  MEDIA_IMAGES_BY_IMAGE_ID: (imageID: string) => `/media/images/${encodeURIComponent(imageID)}`,
  MEDIA_PRODUCT_IMAGES: '/media/product-images',
  MODERATORS: '/moderators',
  NOTIFICATIONS: '/notifications',
  NOTIFICATIONS_BATCH: '/notifications/batch',
  NOTIFICATIONS_CHANNEL_TYPES: '/notifications/channel-types',
  NOTIFICATIONS_CHANNELS: '/notifications/channels',
  NOTIFICATIONS_CHANNELS_BY_ID: (id: string) => `/notifications/channels/${encodeURIComponent(id)}`,
  NOTIFICATIONS_CHANNELS_DETECT_CHAT: '/notifications/channels/detect-chat',
  NOTIFICATIONS_CHANNELS_TEST: (id: string) =>
    `/notifications/channels/${encodeURIComponent(id)}/test`,
  NOTIFICATIONS_COUNT: '/notifications/count',
  NOTIFICATIONS_READ: '/notifications/read',
  NOTIFICATIONS_READ_BY_NOTIF_ID: (notifID: string) =>
    `/notifications/${encodeURIComponent(notifID)}/read`,
  ORDERS: '/orders',
  ORDERS_BY_ORDER_ID: (orderID: string) => `/orders/${encodeURIComponent(orderID)}`,
  ORDERS_CANCEL: (orderID: string) => `/orders/${encodeURIComponent(orderID)}/cancel`,
  ORDERS_CHECKOUT_BREAKDOWN: '/orders/checkout-breakdown',
  ORDERS_COMPLETE: (orderID: string) => `/orders/${encodeURIComponent(orderID)}/complete`,
  ORDERS_CONFIRM: (orderID: string) => `/orders/${encodeURIComponent(orderID)}/confirm`,
  ORDERS_DIGITAL_ASSETS: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/digital-assets`,
  ORDERS_DIGITAL_DELIVERY: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/digital-delivery`,
  ORDERS_DIGITAL_DELIVERY_RETRY: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/digital-delivery/retry`,
  ORDERS_DIGITAL_DOWNLOAD: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/digital-download`,
  ORDERS_ESTIMATE: '/orders/estimate',
  ORDERS_EXTEND_PROTECTION: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/extend-protection`,
  ORDERS_INSTRUCTIONS_CANCEL: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/instructions/cancel`,
  ORDERS_INSTRUCTIONS_COMPLETE: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/instructions/complete`,
  ORDERS_INSTRUCTIONS_CONFIRM: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/instructions/confirm`,
  ORDERS_INSTRUCTIONS_DECLINE: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/instructions/decline`,
  ORDERS_INSTRUCTIONS_REFUND: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/instructions/refund`,
  ORDERS_PAYMENT: (orderID: string) => `/orders/${encodeURIComponent(orderID)}/payment`,
  ORDERS_PAYMENT_CANCEL_PARTIAL: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/payment/cancel-partial`,
  ORDERS_PAYMENT_REMAINING: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/payment/remaining`,
  ORDERS_PAYMENT_SESSION: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/payment-session`,
  ORDERS_PAYMENT_WATCH: (orderID: string) => `/orders/${encodeURIComponent(orderID)}/payment/watch`,
  ORDERS_RATE: (orderID: string) => `/orders/${encodeURIComponent(orderID)}/rate`,
  ORDERS_REFUND: (orderID: string) => `/orders/${encodeURIComponent(orderID)}/refund`,
  ORDERS_REFUND_ADDRESS: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/refund-address`,
  ORDERS_RWA_TOKEN_PAYMENT_INFO: (orderID: string) =>
    `/orders/${encodeURIComponent(orderID)}/rwa-token/payment-info`,
  ORDERS_SETTLEMENT_ACTIONS: (orderID: string, action: string) =>
    `/orders/${encodeURIComponent(orderID)}/settlement-actions/${encodeURIComponent(action)}`,
  ORDERS_SETTLEMENT_ACTIONS_STATUS: (orderID: string, action: string) =>
    `/orders/${encodeURIComponent(orderID)}/settlement-actions/${encodeURIComponent(action)}/status`,
  ORDERS_SHIP: (orderID: string) => `/orders/${encodeURIComponent(orderID)}/ship`,
  ORDERS_SPEND: (orderID: string) => `/orders/${encodeURIComponent(orderID)}/spend`,
  ORDERS_SUPPLY_QUOTE: '/orders/supply-quote',
  PAYMENT_METHODS: (peerID: string) => `/payment-methods/${encodeURIComponent(peerID)}`,
  PEERS: '/peers',
  POSTS: '/posts',
  POSTS_BY_PEER_ID_SLUG: (peerID: string, slug: string) =>
    `/posts/${encodeURIComponent(peerID)}/${encodeURIComponent(slug)}`,
  POSTS_BY_SLUG: (slug: string) => `/posts/${encodeURIComponent(slug)}`,
  PREFERENCES: '/preferences',
  PREFERENCES_CURRENCY: '/preferences/currency',
  PROFILES: '/profiles',
  PROFILES_AVATAR: (peerID: string, size: string) =>
    `/profiles/${encodeURIComponent(peerID)}/avatar/${encodeURIComponent(size)}`,
  PROFILES_BATCH: '/profiles/batch',
  PROFILES_BY_PEER_ID: (peerID: string) => `/profiles/${encodeURIComponent(peerID)}`,
  PROFILES_HEADER: (peerID: string, size: string) =>
    `/profiles/${encodeURIComponent(peerID)}/header/${encodeURIComponent(size)}`,
  PURCHASES: '/purchases',
  RATINGS: (ratingID: string) => `/ratings/${encodeURIComponent(ratingID)}`,
  RATINGS_BATCH: '/ratings/batch',
  RATINGS_INDEX: '/ratings/index',
  RATINGS_INDEX_BY_PEER_ID_SLUG: (peerID: string, slug: string) =>
    `/ratings/index/${encodeURIComponent(peerID)}/${encodeURIComponent(slug)}`,
  RATINGS_INDEX_BY_PEER_IDOR_SLUG: (peerIDOrSlug: string) =>
    `/ratings/index/${encodeURIComponent(peerIDOrSlug)}`,
  RUNTIME_CONFIG: '/runtime-config',
  SALES: '/sales',
  SETTINGS_AI: '/settings/ai',
  SETTINGS_AI_PROVIDERS: '/settings/ai/providers',
  SETTINGS_AI_TEST: '/settings/ai/test',
  SETTINGS_FEATURES: (key: string) => `/settings/features/${encodeURIComponent(key)}`,
  SETTINGS_GUEST_CHECKOUT: '/settings/guest-checkout',
  SETTINGS_GUEST_CHECKOUT_READINESS: '/settings/guest-checkout/readiness',
  SETTINGS_PAYMENT_POLICY: '/settings/payment-policy',
  SETTINGS_PGP_KEY: '/settings/pgp-key',
  SETTINGS_STOREFRONT: '/settings/storefront',
  SETTINGS_STOREFRONT_BY_PEER_ID: (peerID: string) =>
    `/settings/storefront/${encodeURIComponent(peerID)}`,
  SHIPPING_LOCATIONS: '/shipping/locations',
  SHIPPING_LOCATIONS_BY_LOCATION_ID: (locationID: string) =>
    `/shipping/locations/${encodeURIComponent(locationID)}`,
  SHIPPING_PROFILES: '/shipping/profiles',
  SHIPPING_PROFILES_BY_PROFILE_ID: (profileID: string) =>
    `/shipping/profiles/${encodeURIComponent(profileID)}`,
  SHIPPING_PROFILES_LISTINGS: (profileID: string) =>
    `/shipping/profiles/${encodeURIComponent(profileID)}/listings`,
  SHIPPING_PROFILES_SET_DEFAULT: (profileID: string) =>
    `/shipping/profiles/${encodeURIComponent(profileID)}/set-default`,
  SHIPPING_REFRESH_SNAPSHOTS: '/shipping/refresh-snapshots',
  SHIPPING_STALE_LISTINGS: '/shipping/stale-listings',
  STORE_POLICY: '/store-policy',
  STORE_POLICY_MODERATORS: '/store-policy/moderators',
  STORE_POLICY_MODERATORS_BY_PEER_ID: (peerID: string) =>
    `/store-policy/moderators/${encodeURIComponent(peerID)}`,
  STORE_POLICY_PUBLISHED: (peerID: string) =>
    `/store-policy/${encodeURIComponent(peerID)}/published`,
  STORES_LICENSES_ACTIVATE: (storeID: string) =>
    `/stores/${encodeURIComponent(storeID)}/licenses/activate`,
  STORES_LICENSES_DEACTIVATE: (storeID: string) =>
    `/stores/${encodeURIComponent(storeID)}/licenses/deactivate`,
  STORES_LICENSES_VALIDATE: (storeID: string) =>
    `/stores/${encodeURIComponent(storeID)}/licenses/validate`,
  SYSTEM_CACHE: '/system/cache',
  SYSTEM_CLAIM_STORE: '/system/claim-store',
  SYSTEM_CONNECT_PLATFORM: '/system/connect-platform',
  SYSTEM_DIAGNOSTICS: '/system/diagnostics',
  SYSTEM_DOCTOR: '/system/doctor',
  SYSTEM_DOMAIN: '/system/domain',
  SYSTEM_HEALTH: '/system/health',
  SYSTEM_HUMA_PING: '/system/huma-ping',
  SYSTEM_INFO: '/system/info',
  SYSTEM_LOGS: '/system/logs',
  SYSTEM_MCP_CAPABILITY: '/system/mcp/capability',
  SYSTEM_MCP_CLIENTS: '/system/mcp/clients',
  SYSTEM_MCP_CONNECT: '/system/mcp/connect',
  SYSTEM_MCP_CONNECT_BY_CLIENT: (client: string) =>
    `/system/mcp/connect/${encodeURIComponent(client)}`,
  SYSTEM_MCP_DISCONNECT: '/system/mcp/disconnect',
  SYSTEM_MCP_DISCONNECT_BY_CLIENT: (client: string) =>
    `/system/mcp/disconnect/${encodeURIComponent(client)}`,
  SYSTEM_NETWORK: '/system/network',
  SYSTEM_PUBLISH: '/system/publish',
  SYSTEM_SETUP: '/system/setup',
  SYSTEM_SHUTDOWN: '/system/shutdown',
  SYSTEM_UPDATE_CONFIG: '/system/update-config',
  SYSTEM_UPDATE_TRIGGER: '/system/update-trigger',
  WALLET_CURRENCIES: '/wallet/currencies',
  WALLET_MNEMONIC: '/wallet/mnemonic',
  WALLET_RECEIVING_ACCOUNTS: '/wallet/receiving-accounts',
  WALLET_RECEIVING_ACCOUNTS_BY_ID: (id: string) =>
    `/wallet/receiving-accounts/${encodeURIComponent(id)}`,
  WALLET_SPEND: '/wallet/spend',
  WEBHOOKS: '/webhooks',
  WEBHOOKS_BY_ID: (id: string) => `/webhooks/${encodeURIComponent(id)}`,
  WEBHOOKS_DELIVERIES: (id: string) => `/webhooks/${encodeURIComponent(id)}/deliveries`,
  WEBHOOKS_TEST: (id: string) => `/webhooks/${encodeURIComponent(id)}/test`,
  WISHLISTS: '/wishlists',
  WISHLISTS_BY_PEER_ID_SLUG: (peerID: string, slug: string) =>
    `/wishlists/${encodeURIComponent(peerID)}/${encodeURIComponent(slug)}`,
} as const;
